import SideBar from '../components/sidebar/sidebar'
import Actpic from '../components/activitypicture/act_pic'
import  styles  from '../styles/catalog.module.css'
import { useEffect, useState } from 'react';
import axios from 'axios';
import Head from 'next/head';
import Profilesmall from '../components/common/Profilesmall';



interface Picture{
    name : string;
    img_url : string;
    id : number

}

interface Prop{
        pic1 : Picture[]
        pic2 : Picture[]
    }


 function Catalog(){
    const[games,setgames] = useState<Picture[]>([])
    const[outdoors,setoutdoors] = useState<Picture[]>([])

    useEffect (()=>{
        console.log("dddddddddd")
        axios.get<Picture[]>('https://harty.onfirebyte.xyz/activities',  {params:{category:"OnlineGame"}}   ).then((v)=>{
            setgames(v.data)
        })
        axios.get<Picture[]>('https://harty.onfirebyte.xyz/activities',  {params:{category:"OutdoorActivity"}}   ).then((v)=>{
            setoutdoors(v.data)
        })


    },[ ])
    
    const [isShowMoreG,setShowG] = useState(false)
    function showhideG(){
        setShowG(!isShowMoreG);
    }
    const [isShowMoreA,setShowA] = useState(false)
    function showhideA(){
        setShowA(!isShowMoreA);
    }

    return (
        <div className={styles.container}>
        <Head>
        <title>Harty | Catalog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/hartyicon.svg" />
        </Head>
        <div style={{display : 'flex' , backgroundColor : '#16213E' , height : "100%" , width : "100%"}} >
                <div className={styles.navbar}>
                    <h1 style={{marginLeft: '79px'}}>Catalog</h1>
                    <div style={{width: '50px', height: '50px', position: 'absolute', right: '10px'}}>
                        <Profilesmall image = "https://cdn.discordapp.com/attachments/1031508000151707718/1034905338345951272/unknown.png"/>
                    </div>
                </div>
                <SideBar/>
                <div style={{display:"inline-block"}}>
                <div className={styles.bar_cat}>Online Game</div>

                <div className={styles.box}>
                    <div className={styles.pic}>
                        {
                            isShowMoreG ? (games.map((v,i)=>(
                            <div style={{margin : "15px"}} key={v.id}>
                                <Actpic  name = {v.name} URL = {v.img_url} id = {v.id}/>
                            </div>
                            ))) 
                            : (games.slice(0,8).map((v,i)=>(
                                <div style={{margin : "15px"}} key={v.id}>
                                    <Actpic  name = {v.name} URL = {v.img_url} id = {v.id} />
                                </div>
                                )))
                        }
                    </div>
                        <div style={{margin : "auto"}}>
                            <button className={styles.show} onClick = {showhideG} > {!isShowMoreG ? "Show More v" : "Show Less ^"} </button>
                        </div>
                </div>

                <div className={styles.bar_cat}>Outdoor Activity</div>

                <div className={styles.box}>
                    <div className={styles.pic}>
                        {
                            isShowMoreA ? (outdoors.map((v,i)=>(
                            <div style={{margin : "15px"}} key={v.id}>
                                <Actpic  name = {v.name} URL = {v.img_url}  id = {v.id}/>
                            </div>
                            ))) 
                            :    (outdoors.slice(0,8).map((v,i)=>(
                                <div style={{margin : "15px"}} key={v.id}>
                                    <Actpic  name = {v.name} URL = {v.img_url} id = {v.id}/>
                                </div>
                                )))
                        }
                    </div>
                        <div style={{margin : "auto"}}>
                            <button className={styles.show} onClick = {showhideA} > {!isShowMoreA ? "Show more v" : "Show Less ^"} </button>
                        </div>
                </div>
                </div>
        </div>
        </div>             
    )
}
export default Catalog