import Head from "next/head"
import styles from "../styles/explore.module.css"
import SideBar from "../components/sidebar/sidebar"
import PartyCards from "../components/common/PartyCards"

const Explore = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Harty | Explore</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/hartyicon.svg" />
            </Head>
            <main className = {styles.main}>
                <div className={styles.navbar}>
                    <h1 style={{marginLeft: '79px'}}>Explore</h1>
                </div>
                <div className={styles.content}>
                    <div style = {{width: '80%', borderRadius: '30px'}}>
                        <PartyCards path='party/'/>
                    </div>
                </div>
                <SideBar />
            </main>
            
        </div>

    )
}

export default Explore