import type { NextPage } from 'next'
import SideBar from '../components/sidebar/sidebar'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { CardnModal } from '../components/common/CardnModal'
import PartyCards from '../components/common/PartyCards'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Harty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hartyicon.svg" />
      </Head>
      <main className={styles.main}>
        <div>
          <SideBar />
        </div>
        <div className={styles.feed}>
          <PartyCards/>
        </div>
      </main>  
    </div>
  )
}

export default Home
