import type { NextPage } from 'next'
import SideBar from '../components/sidebar/sidebar'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import PartyCards from '../components/common/PartyCards'
import Category from '../components/category/Category'
import {useRef} from 'react'
import Profilesmall from '../components/common/Profilesmall'
import NewsPane from '../components/common/NewsPane'

const Home: NextPage = () => {
  const ref1 = useRef<null | HTMLDivElement>(null); 
  const handleActClick = () => {
    ref1.current?.scrollIntoView({behavior: 'smooth'})
  }
  const ref2 = useRef<null | HTMLDivElement>(null); 
  const handleGameClick = () => {
    ref2.current?.scrollIntoView({behavior: 'smooth'})
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Harty | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hartyicon.svg" />
      </Head>
      <main className={styles.main}>
        <div className={styles.navbar}>
            <h1 style={{marginLeft: '79px'}}>Home</h1>
            <div style={{width: '50px', height: '50px', position: 'absolute', right: '10px'}}>
              <Profilesmall image = "https://cdn.discordapp.com/attachments/1031508000151707718/1034905338345951272/unknown.png"/>
            </div>
        </div>
        <div>
          <SideBar />
        </div>
        <div className={styles.rightContainer}>
          <div className={styles.navbarplaceholder}>
          </div>
          <div className={styles.feed}>
            <div style={{marginTop: '30px'}}>
              <NewsPane/>
            </div>
            <Category onGameClick={() => {handleGameClick()}} onActClick={() => {handleActClick()}}/>
            <div ref = {ref2} style = {{backgroundColor: 'white', margin: '50px 0px', marginTop: '76px', width: '80%', borderRadius: '30px'}}>
              <h1 style={{color: 'black', margin: '0px 0px', marginLeft: '10px'}}>Online Game</h1>
            </div>
            <div style={{width: '80%', borderRadius: '30px'}}>
              <PartyCards path='party/category?category=OnlineGame'/>
            </div>
            <div ref = {ref1} style = {{backgroundColor: 'white', margin: '50px 0px', marginTop: '76px', width: '80%', borderRadius: '30px', justifyItems: 'center'}}>
              <h1 style={{color: 'black', margin: '0px 0px', marginLeft: '10px'}}>Outdoor Activities</h1>
            </div>
            <div style={{width: '80%', borderRadius: '30px'}}>
              <PartyCards path='party/category?category=OutdoorActivity'/>
            </div>
          </div>
        </div>
      </main>  
    </div>
  )
}

export default Home
