import type { NextPage } from 'next'
import SideBar from '../components/sidebar/sidebar'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { CardnModal } from '../components/common/CardnModal'
import PartyCards from '../components/common/PartyCards'
import Category from '../components/category/Category'
import {useRef} from 'react'

const Home: NextPage = () => {
  const ref1 = useRef<null | HTMLDivElement>(null); 
  const handleActClick = () => {
    ref1.current?.scrollIntoView({behavior: 'smooth'})
  }
  const ref2 = useRef<null | HTMLDivElement>(null); 
  const handleGameClick = () => {
    ref2.current?.scrollIntoView({behavior: 'smooth'})
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Harty | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hartyicon.svg" />
      </Head>
      <main className={styles.main}>
        <div className={styles.navbar}>
            <h1 style={{marginLeft: '79px'}}>Home</h1>
            </div>
        <div>
          <SideBar />
        </div>
        <div className={styles.rightContainer}>
          <div className={styles.navbarplaceholder}>
          </div>
          <div className={styles.feed}>
            <Category onGameClick={() => {handleGameClick()}} onActClick={() => {handleActClick()}}/>
            <div ref = {ref2} style = {{backgroundColor: 'white', margin: '20px 0px', marginTop: '36px', height: '36px', width: '80%', borderRadius: '30px'}}>
              <h2 style={{color: 'black', margin: '0px 0px', marginLeft: '10px'}}>Online Game</h2>
            </div>
            <div style={{width: '80%', borderRadius: '30px'}}>
              <PartyCards path='party/'/>
            </div>
            <div ref = {ref1} style = {{backgroundColor: 'white', margin: '20px 0px', height: '36px', width: '80%', borderRadius: '30px'}}>
              <h2 style={{color: 'black', margin: '0px 0px', marginLeft: '10px'}}>Outdoor Activities</h2>
            </div>
            <div style={{width: '80%', borderRadius: '30px'}}>
              <PartyCards path='party/'/>
            </div>
          </div>
        </div>
      </main>  
    </div>
  )
}

export default Home
