import Head from 'next/head'
import LeftContainer from '../components/login/LeftContainer'
import LoginCard from '../components/login/LoginCard'
import SignIn from '../components/login/SignIn'

import styles from '../styles/Login.module.css'
const Login = () =>{
    return <div className={styles.container}>
        <Head>
      <title>Harty | Login</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/hartyicon.svg" />
    </Head>
        <LeftContainer/>
            <div className={styles.loginContainer}>
                <LoginCard title='Sign In'><SignIn/></LoginCard>
            </div>
    </div>
}




export default Login