import Head from 'next/head'
import { useState } from 'react'
import ReactCardFlip from 'react-card-flip'
import LeftContainer from '../components/login/LeftContainer'
import LoginCard from '../components/login/LoginCard'
import SignIn from '../components/login/SignIn'
import SignUp from '../components/login/Signup'

import styles from '../styles/Login.module.css'
const Login = () =>{
    const [isFliped,setFliped] = useState(true);

    return <div className={styles.container}>
        <Head>
      <title>Harty | Login</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/hartyicon.svg" />
    </Head>
        <LeftContainer/>
            <div className={styles.loginContainer}>
                <ReactCardFlip isFlipped={isFliped} 
                flipDirection="horizontal">
                <LoginCard title='Sign In' hasAccount="Don't have an account?" url="/signup" asUrl="/signup" onHasAccountClick={()=>setFliped(v=>!v)}><SignIn /></LoginCard>
                <LoginCard title='Create an account' hasAccount="Already have an account?" url="/signup" asUrl="/login" onHasAccountClick={()=>setFliped(v=>!v)}><SignUp/></LoginCard>
                </ReactCardFlip>
            </div>
    </div>
}




export default Login